.\" Copyright (c) 2010 Svante J. Kvarnstrom <sjk@ankeborg.nu>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.TH BLOCK 1
.SH NAME
block - add specified addresses to firewall block tables
.SH SYNOPSIS
.B block
[\-hkK] [\-t <table>] <ip adresses>
.SH DESCRIPTION
.B block 
attempts to add IP addresses to a PF table and may also be instructed 
to kill any states originating from the IP addresses in question. If the user is not
the super user the program will attempt to use sudo when adding the IP addresses.
.SH OPTIONS
.TP 
\-h 
Show short help 
.TP
-k
Kill states originating from listed IP addresses
.TP
-K 
Only kills states and does not add addresses to table.
.TP
-t <table> 
Add addresses to specified table instead of the default (badips)
.SH REQUIREMENTS
One or several pf tables with appropriate (block) rules must be configured
in your
.B /etc/pf.conf
.SH EXAMPLES
To add IP addresses 192.8.9.8 and 18.7.8.9 to table 
.B drones
as well as killing any states originating from any of the
two addresses one would use:
.TP
.B block 
-kt drones 192.8.9.8 18.7.8.9
.PP
For the above command to be effective your 
.B pf.conf
must include something like the following:
.PP
table <drones>
.PP
block drop in log quick on $ext_if from <drones> to ($ext_if) 
.SH FILES
.I /etc/pf.conf
.I /usr/local/etc/sudoers
.SH SEE ALSO
pfctl(8),
sudo(8)
.SH AUTHOR
Svante J Kvarnstrom <sjk@ankeborg.nu>
