.\" Copyright (c) 2010 Svante J. Kvarnstrom <sjk@ankeborg.nu>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.TH BLOCK 1
.SH NAME
unblock - removes specified addresses from firewall block tables
.SH SYNOPSIS
.B unblock
[\-h] [\-t <table>] <ip adresses>
.SH DESCRIPTION
.B unblock 
attemts to remove IP addresses from a PF table. If the user is not the super user the
program will attempt to use sudo when calling pfctl(8).
.SH OPTIONS
.TP 
\-h 
Show short help 
.TP
-t <table> 
Add addresses to specified table instead of the default (badips)
.SH REQUIREMENTS
One or several pf tables with appropriate (block) rules must be configured
in your
.B /etc/pf.conf
.SH EXAMPLES
To remove the IP addresses 192.8.9.8 and 18.7.8.9 from the drones table one would use
.TP
.B unblock 
-t drones 192.8.9.8 18.7.8.9
.PP
.SH FILES
.I /etc/pf.conf
.I /usr/local/etc/sudoers
.SH SEE ALSO
pfctl(8),
sudo(8)
.SH AUTHOR
Svante J Kvarnstrom <sjk@ankeborg.nu>
